---
abstract: 'a common interface for type constraints, based on observed patterns (documentation only)'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Type::API
name: Type-API
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  perl: 5.005
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Type-API
  homepage: https://metacpan.org/release/Type-API
  license: http://dev.perl.org/licenses/
  repository: https://github.com/tobyink/docs-type-api
version: 0.001
